"""
Django settings for jmw project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from environs import Env
import os
import json

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

if not DEBUG:
    ALLOWED_HOSTS = [
        "jmw-accessories.onrender.com",
        "www.jumemegawears.com",
        "jumemegawears.com",
    ]

    CSRF_TRUSTED_ORIGINS = [
    ]
else:
    ALLOWED_HOSTS = [".ngrok-free.app", "localhost", "127.0.0.1"]

    CSRF_TRUSTED_ORIGINS = [
        "https://*.ngrok-free.app",
    ]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.sites",
    # Third-party
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "tailwind",
    "theme",
    "cloudinary_storage",
    "django.contrib.staticfiles",
    "cloudinary",
    "debug_toolbar",
    # local
    "accounts.apps.AccountsConfig",
    "pages.apps.PagesConfig",
    "products.apps.ProductsConfig",
    "cart.apps.CartConfig",
    "blog.apps.BlogConfig",
    "measurement.apps.MeasurementConfig",
    "feed.apps.FeedConfig",
    "order.apps.OrderConfig",
    "payment.apps.PaymentConfig",
    "bulk_orders.apps.BulkOrdersConfig",
    "comments.apps.CommentsConfig",
    "webhook_router.apps.WebhookRouterConfig",
    "email_tracking.apps.EmailTrackingConfig",
    "orderitem_generation.apps.OrderitemGenerationConfig",
    "cached.apps.CachedConfig",
]
if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "cart.middleware.CartCleanupMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]
if DEBUG:
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = "jmw.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "jmw.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": env.dj_db_url("DATABASE_URL", default="postgres://postgres@db/postgres")
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"  # Nigeria's timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# custom user
AUTH_USER_MODEL = "accounts.CustomUser"

# django-allauth config
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "pages:home"
ACCOUNT_LOGOUT_REDIRECT = "pages:home"
SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
SOCIALACCOUNT_LOGIN_ON_GET = True
ADMINS = [("Ifeanyi Nnamani", "ifeanyinnamani@jumemegawears.com")]
SERVER_EMAIL = "server@jumemegawears.com"


if DEBUG:
    # Create a single email directory for file-based emails
    EMAIL_FILE_PATH = str(BASE_DIR / "sent_emails")
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = str(BASE_DIR / "sent_emails")
else:
    # Email Configuration
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.zoho.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = "ifeanyinnamani@jumemegawears.com"
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")


# EMAIL_BACKEND = "django_ses.SESBackend"

# # AWS SES
# AWS_SES_ACCESS_KEY_ID = env.str("AWS_SES_ACCESS_KEY_ID")
# AWS_SES_SECRET_ACCESS_KEY = env.str("AWS_SES_SECRET_ACCESS_KEY")
# AWS_SES_REGION_NAME = "eu-north-1"
# AWS_SES_REGION_ENDPOINT = "email.eu-north-1.amazonaws.com"
# AWS_SES_AUTO_THROTTLE = 0.5
# AWS_SES_CONFIGURATION_SET = "Jmw_AccessoriesEmailTracking"

# SNS Topics ARNs (replace with your actual ARNs from AWS Console)
AWS_SNS_TOPICS = {
    "bounces": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-bounces",
    "complaints": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-complaints",
    "delivery": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-delivery",
    "clicks": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-clicks",
    "opens": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-opens",
    "rejects": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-rejects",
    "rendering_failures": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-rendering-failures",
    "delivery_delays": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-delivery-delays",
    "sends": "arn:aws:sns:eu-north-1:194722423613:jmw-ses-sends",
}

DEFAULT_FROM_EMAIL = "JMW <info@jumemegawears.com>"
CONTACT_EMAIL = "contact@jumemegawears.com"

# Cloudinary settings
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": env("CLOUD_NAME"),
    "API_KEY": env("CLOUD_API_KEY"),
    "API_SECRET": env("CLOUD_API_SECRET"),
    "STATICFILES_MANIFEST_ROOT": os.path.join(BASE_DIR, "manifest"),
    "STATIC_IMAGES_EXTENSIONS": [
        "jpg",
        "jpe",
        "jpeg",
        "jpc",
        "jp2",
        "j2k",
        "wdp",
        "jxr",
        "hdp",
        "png",
        "gif",
        "webp",
        "bmp",
        "tif",
        "tiff",
        "ico",
    ],
    "MEDIA_EXTENSIONS": [
        "jpg",
        "jpe",
        "jpeg",
        "jpc",
        "jp2",
        "j2k",
        "wdp",
        "jxr",
        "hdp",
        "png",
        "gif",
        "webp",
        "bmp",
        "tif",
        "tiff",
        "ico",
    ],
}

# Media files
MEDIA_URL = "/media/" 
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# This should come after CLOUDINARY_STORAGE settings
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_SECRET"),
        },
        "SCOPE": [
            "profile",
            "email",
        ],
    },
    "github": {
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID"),
            "secret": env("GITHUB_SECRET"),
        },
        "SCOPE": ["read:user", "user:email"],
    },
}


# whitenoise
if DEBUG == False:
    WHITENOISE_AUTOREFRESH = False
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False


TAILWIND_APP_NAME = "theme"
# INTERNAL_IPS = ["127.0.0.1"]

# Ensure npm can be found in the Docker container
NPM_BIN_PATH = "npm"

# cart
CART_SESSION_ID = "cart"


# log settings

# Ensure logs directory exists and has proper permissions
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)
os.chmod(LOGS_DIR, 0o755)

# Create log files with proper permissions
LOG_FILES = ["debug.log", "info.log", "error.log", "critical.log", "daily.log"]
for log_file in LOG_FILES:
    log_path = LOGS_DIR / log_file
    if not log_path.exists():
        log_path.touch()
    os.chmod(log_path, 0o644)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "detailed": {
            "format": "{levelname} {asctime} {name} {module} {funcName} {lineno} {message}",
            "style": "{",
        },
        "security": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message} {request.META.REMOTE_ADDR}",
            "style": "{",
        },
        "performance": {
            "format": "{levelname} {asctime} {module} {message} Duration: {duration:.2f}ms",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "filters": ["require_debug_true"] if DEBUG else ["require_debug_false"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "debug.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 10,
            "formatter": "detailed",
        },
        "file_info": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "info.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 10,
            "formatter": "verbose",
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "error.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 10,
            "formatter": "detailed",
        },
        "critical_errors": {
            "level": "CRITICAL",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "critical.log"),
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 30,
            "formatter": "detailed",
        },
        "timed_rotating_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(LOGS_DIR / "daily.log"),
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
            "formatter": "detailed",
            "include_html": True,  # Includes HTML version of the error
        },
    },
    "loggers": {
        "": {  # Root logger
            "handlers": ["console", "file_info", "file_error", "timed_rotating_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
        "django": {
            "handlers": ["console", "file_info", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console", "file_info"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file_error", "mail_admins", "critical_errors"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["file_debug"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["file_error", "mail_admins", "critical_errors"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security.csrf": {
            "handlers": ["file_error", "mail_admins", "critical_errors"],
            "level": "WARNING",
            "propagate": False,
        },
        "pages": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "accounts": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "payment": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "order": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "bulk_orders": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "ratings": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "blog": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "cart": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "comments": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "email_tracking": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "feed": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "measurement": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "orderitem_generation": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "products": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "tracking": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "webhook_router": {
            "handlers": ["console", "file_debug", "file_info", "file_error"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


YOUTUBE_API_KEY = env.str("YOUTUBE_API_KEY")
YOUTUBE_CHANNEL_ID = env.str("YOUTUBE_CHANNEL_ID")

# Paystack settings
if DEBUG:
    PAYSTACK_TEST_SECRET_KEY = env("PAYSTACK_TEST_SECRET_KEY")
    PAYSTACK_TEST_PUBLIC_KEY = env("PAYSTACK_TEST_PUBLIC_KEY")
else:
    PAYSTACK_LIVE_SECRET_KEY = env("PAYSTACK_LIVE_SECRET_KEY")
    PAYSTACK_LIVE_PUBLIC_KEY = env("PAYSTACK_LIVE_PUBLIC_KEY")


# Company details for receipt (bulk_orders)
COMPANY_ADDRESS = "16 Emejiaka Street, Ngwa Rd, Aba Abia State"
COMPANY_PHONE = "+2348139425458"
COMPANY_EMAIL = "info@jumemegawears.com"

# django-debug-toolbar
import socket

hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[:-1] + "1" for ip in ips]


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    }
}

# deployment checklist
SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=2592000)  # 30 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
)
SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
