# Generated by Django 5.1.3 on 2026-01-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address_order_city_order_reference_order_state_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='order.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was verified', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='payments', to='order.order'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='payment_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paystack_reference'], name='payment_paystack_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['email'], name='payment_email_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['-created'], name='payment_created_idx'),
        ),
    ]
