# Generated by Django 5.1.3 on 2025-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_testimonial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.URLField()),
            ],
        ),
    ]
