# Generated by Django 5.1.3 on 2025-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_testimonial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomessage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
