# Generated by Django 5.1.3 on 2024-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='JMW & ACCESSORIES', max_length=20, verbose_name='Author'),
        ),
    ]
