# Generated by Django 5.1.3 on 2024-12-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dhhaiy58r/image/upload/v1686407057/jume_others/46_uhpdya.jpg', max_length=600),
        ),
    ]
