# Generated by Django 5.1.3 on 2025-01-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dhhaiy58r/image/upload/v1721420288/Black_White_Minimalist_Clothes_Store_Logo_e1o8ow.png', max_length=600),
        ),
    ]
