# Generated by Django 5.1.3 on 2025-01-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkorderlink',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='orderentry',
            name='payment_reference',
        ),
    ]
