# Generated by Django 5.1.3 on 2026-01-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0002_bulkorderlink_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['updated_at'], name='order_updated_idx'),
        ),
    ]
