# Generated by Django 5.1.3 on 2025-01-07 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0002_remove_bulkorderlink_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentry',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['created_by', 'payment_deadline'], name='bulk_order_user_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['organization_name'], name='bulk_order_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['created_at'], name='bulk_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['bulk_order', 'is_used'], name='coupon_bulk_order_used_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['code'], name='coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['bulk_order', 'serial_number'], name='order_bulk_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['email'], name='order_email_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['paid'], name='order_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['size'], name='order_size_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['created_at'], name='order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['payment_reference'], name='order_payment_ref_idx'),
        ),
    ]
