# Generated by Django 5.1.3 on 2025-01-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0003_orderentry_payment_reference_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderentry',
            name='order_payment_ref_idx',
        ),
        migrations.RemoveField(
            model_name='orderentry',
            name='payment_reference',
        ),
    ]
