# Generated by Django 5.1.3 on 2024-12-19 17:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
