# Generated by Django 5.1.3 on 2025-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_youtubecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, upload_to='feed/'),
        ),
    ]
