# Generated by Django 5.1.3 on 2025-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
        migrations.CreateModel(
            name='CacheSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('cache_timeout', models.PositiveIntegerField(default=900, help_text='Cache timeout in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('last_cleared', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
