# Generated by Django 5.1.3 on 2025-01-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField()),
                ('raw_data', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['message_id'], name='email_track_message_eb64b1_idx'), models.Index(fields=['event_type'], name='email_track_event_t_79e9cb_idx'), models.Index(fields=['timestamp'], name='email_track_timesta_d934fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=50, null=True)),
                ('feedback_id', models.CharField(max_length=100, null=True)),
                ('email_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='email_tracking.emailevent')),
            ],
        ),
        migrations.CreateModel(
            name='Bounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounce_type', models.CharField(max_length=50)),
                ('bounce_subtype', models.CharField(max_length=50)),
                ('email_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='email_tracking.emailevent')),
            ],
        ),
    ]
