# Generated by Django 5.1.3 on 2025-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('app_name', models.CharField(max_length=50)),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
