# Generated by Django 5.1.3 on 2025-01-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_tracking', '0002_failedreceipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedReceipt',
        ),
    ]
