# Generated by Django 5.1.3 on 2024-12-28 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysckitorder',
            name='state_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid NYSC state code (e.g., AB/22C/1234)', regex='^[A-Z]{2}/\\d{2}[A-Z]/\\d{4}$')]),
        ),
    ]
