# Generated by Django 5.1.3 on 2024-12-28 20:34

import order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_nysckitorder_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysckitorder',
            name='state_code',
            field=models.CharField(max_length=11, validators=[order.validators.validate_state_code]),
        ),
    ]
