# Generated by Django 5.1.3 on 2026-01-08 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - marks measurement as deleted without removing from database'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['user', '-created_at'], name='measurement_user_created_idx'),
        ),
    ]
