# Generated by Django 5.1.3 on 2024-12-11 15:54

import django.core.validators
import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_type', models.CharField(choices=[('nysc_kit', 'NYSC Kit'), ('nysc_tour', 'NYSC Tour'), ('church', 'CHURCH')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_693421_idx'), models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'), models.Index(fields=['product_type'], name='products_ca_product_9e88ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_1', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_2', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_3', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('available', models.BooleanField(default=True, help_text='Controls whether the product is visible on the site')),
                ('out_of_stock', models.BooleanField(default=False, help_text='Controls whether the product can be purchased')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_name_choice', models.CharField(blank=True, choices=[('quality_shilo_shirt', 'QUALITY SHILO SHIRT'), ('quality_rccg_shirt', 'QUALITY RCCG SHIRT')], max_length=100, null=True, verbose_name='Product Name')),
                ('church', models.CharField(choices=[('shilo', 'SHILO'), ('rccg', 'RCCG CONVENTION')], max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('custom_name', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='products_ch_name_5c0722_idx'), models.Index(fields=['slug'], name='products_ch_slug_7ec679_idx'), models.Index(fields=['available', 'out_of_stock'], name='products_ch_availab_453360_idx'), models.Index(fields=['created'], name='products_ch_created_23eb60_idx'), models.Index(fields=['church', 'size'], name='products_ch_church_e24de1_idx')],
            },
        ),
        migrations.CreateModel(
            name='NyscKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_1', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_2', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_3', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('available', models.BooleanField(default=True, help_text='Controls whether the product is visible on the site')),
                ('out_of_stock', models.BooleanField(default=False, help_text='Controls whether the product can be purchased')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_name_choice', models.CharField(blank=True, choices=[('Quality Nysc Kakhi', 'Quality Nysc Kakhi'), ('Quality Nysc Vest', 'Quality Nysc Vest'), ('Quality Nysc Cap', 'Quality Nysc Cap')], max_length=100, null=True, verbose_name='Product Name')),
                ('type', models.CharField(choices=[('kakhi', 'kakhi'), ('vest', 'vest'), ('cap', 'cap')], max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='products_ny_name_d97dca_idx'), models.Index(fields=['slug'], name='products_ny_slug_5d85ca_idx'), models.Index(fields=['available', 'out_of_stock'], name='products_ny_availab_69a3fc_idx'), models.Index(fields=['created'], name='products_ny_created_98b2b8_idx'), models.Index(fields=['type', 'size'], name='products_ny_type_0c0a60_idx')],
            },
        ),
        migrations.CreateModel(
            name='NyscTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_1', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_2', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('image_3', models.URLField(blank=True, max_length=600, validators=[products.models.validate_image_url])),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('available', models.BooleanField(default=True, help_text='Controls whether the product is visible on the site')),
                ('out_of_stock', models.BooleanField(default=False, help_text='Controls whether the product can be purchased')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_name_choice', models.CharField(blank=True, choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'FCT'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=100, null=True, verbose_name='Product Name')),
                ('Nysc_call_up_number', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='products_ny_name_3f5c75_idx'), models.Index(fields=['slug'], name='products_ny_slug_dcf337_idx'), models.Index(fields=['available', 'out_of_stock'], name='products_ny_availab_75f466_idx'), models.Index(fields=['created'], name='products_ny_created_c5d833_idx'), models.Index(fields=['Nysc_call_up_number'], name='products_ny_Nysc_ca_250e20_idx')],
            },
        ),
    ]
