# Generated by Django 5.1.3 on 2026-01-02 14:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='church',
            name='image_1',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='church',
            name='image_2',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='church',
            name='image_3',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='image_1',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='image_2',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='image_3',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysctour',
            name='image',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysctour',
            name='image_1',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysctour',
            name='image_2',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='nysctour',
            name='image_3',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/'),
        ),
    ]
