# Generated by Django 5.1.3 on 2024-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysckit',
            name='size',
            field=models.CharField(help_text='Size is automatically set for Kakhi and Cap products. For Vests, size must be selected from standard options.', max_length=20),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='type',
            field=models.CharField(choices=[('kakhi', 'kakhi'), ('vest', 'vest'), ('cap', 'cap')], help_text='Select the type of NYSC Kit product', max_length=20),
        ),
    ]
