# Generated by Django 5.1.3 on 2024-12-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_nysckit_size_alter_nysckit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nysckit',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nysctour',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='church',
            name='products_ch_availab_453360_idx',
        ),
        migrations.RemoveIndex(
            model_name='church',
            name='products_ch_created_23eb60_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_availab_69a3fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_created_98b2b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysctour',
            name='products_ny_availab_75f466_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysctour',
            name='products_ny_created_c5d833_idx',
        ),
        migrations.RemoveField(
            model_name='church',
            name='product_name_choice',
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='product_name_choice',
        ),
        migrations.RemoveField(
            model_name='nysctour',
            name='product_name_choice',
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(choices=[('quality_shilo_shirt', 'QUALITY SHILO SHIRT'), ('quality_rccg_shirt', 'QUALITY RCCG SHIRT')], max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='name',
            field=models.CharField(choices=[('Quality Nysc Kakhi', 'Quality Nysc Kakhi'), ('Quality Nysc Vest', 'Quality Nysc Vest'), ('Quality Nysc Cap', 'Quality Nysc Cap')], max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='size',
            field=models.CharField(help_text='Size handling varies by product type', max_length=20),
        ),
        migrations.AlterField(
            model_name='nysctour',
            name='name',
            field=models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'FCT'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=100, verbose_name='Product Name'),
        ),
    ]
