# Generated by Django 5.1.3 on 2024-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_church_options_alter_nysckit_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_type_0c0a60_idx',
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='size',
        ),
        migrations.AddField(
            model_name='nysckit',
            name='size_cap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nysckit',
            name='size_kakhi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nysckit',
            name='size_vest',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('NYSC KIT', 'NYSC KIT'), ('NYSC TOUR', 'NYSC TOUR'), ('CHURCH PROG', 'CHURCH PROG')], max_length=200),
        ),
        migrations.AlterField(
            model_name='church',
            name='church',
            field=models.CharField(choices=[('WINNERS', 'WINNERS'), ('RCCG', 'RCCG')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='nysckit',
            index=models.Index(fields=['type', 'size_kakhi', 'size_cap', 'size_vest'], name='products_ny_type_5c87a0_idx'),
        ),
    ]
