# Generated by Django 5.1.3 on 2024-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_nysckit_products_ny_type_0c0a60_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='church',
            name='products_ch_church_e24de1_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_type_5c87a0_idx',
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='size_cap',
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='size_kakhi',
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='size_vest',
        ),
        migrations.AddField(
            model_name='nysckit',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], help_text="Size is applicable for 'vest' only.", max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['church'], name='products_ch_church_ab62ba_idx'),
        ),
        migrations.AddIndex(
            model_name='nysckit',
            index=models.Index(fields=['type'], name='products_ny_type_c88e72_idx'),
        ),
    ]
