# Generated by Django 5.1.3 on 2024-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_church_products_ch_church_e24de1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nysckit',
            name='size_vest',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], help_text="Applicable only for 'vest' type.", max_length=5, null=True),
        ),
    ]
