# Generated by Django 5.1.3 on 2024-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_nysckit_size_vest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nysckit',
            options={'ordering': ['id'], 'verbose_name': 'NYSC Kit', 'verbose_name_plural': 'NYSC Kits'},
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='size_vest',
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], help_text='Size varies based on product type: Measurement for kakhi, Free Size for cap, S/M/L/XL for vest', max_length=20, null=True),
        ),
    ]
