# Generated by Django 5.1.3 on 2024-12-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_nysckit_options_remove_nysckit_size_vest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nysckit',
            options={'ordering': [models.Case(models.When(then=0, type='kakhi'), models.When(then=2, type='vest'), models.When(then=1, type='cap'), default=3), 'type']},
        ),
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_name_d97dca_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_slug_5d85ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='nysckit',
            name='products_ny_type_c88e72_idx',
        ),
        migrations.AlterField(
            model_name='nysckit',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
