# Generated by Django 5.1.3 on 2024-12-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_nysckit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['id'], 'verbose_name': 'church', 'verbose_name_plural': 'churchies'},
        ),
        migrations.AlterModelOptions(
            name='nysctour',
            options={'ordering': ['id'], 'verbose_name': 'nysctour', 'verbose_name_plural': 'nysctours'},
        ),
        migrations.RemoveIndex(
            model_name='nysctour',
            name='products_ny_Nysc_ca_250e20_idx',
        ),
        migrations.RemoveField(
            model_name='church',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='church',
            name='size',
        ),
        migrations.RemoveField(
            model_name='nysckit',
            name='size',
        ),
        migrations.RemoveField(
            model_name='nysctour',
            name='Nysc_call_up_number',
        ),
    ]
