# Generated by Django 5.1.3 on 2025-01-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_church_options_alter_nysctour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(choices=[('Quality Shilo Shirt', 'QUALITY SHILO SHIRT'), ('Quality RCCG Shirt', 'QUALITY RCCG SHIRT')], max_length=100, verbose_name='Product Name'),
        ),
    ]
