# Generated by Django 5.1.3 on 2025-01-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_church_image_alter_church_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('nysc_kit', 'NYSC Kit'), ('nysc_tour', 'NYSC Tour'), ('church', 'Church')], max_length=20)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Countdown Timer',
                'verbose_name_plural': 'Countdown Timers',
            },
        ),
    ]
