# Generated by Django 5.1.3 on 2025-01-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_countdowntimer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountdownTimer',
        ),
    ]
