# Generated by Django 5.1.3 on 2025-02-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_nysctour_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nysctour',
            options={'ordering': ['name'], 'verbose_name': 'nysctour', 'verbose_name_plural': 'nysctours'},
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(choices=[('Quality Shilo Shirt', 'QUALITY SHILO SHIRT'), ('Quality RCCG Shirt', 'QUALITY RCCG SHIRT'), ('Quality RCCG Shirt jacket', 'QUALITY RCCG JACKET'), ('Quality shilo jacket', 'QUALITY SHILO JACKET'), ('Quality RCCG polo', 'QUALITY RCCG POLO'), ('Quality shilo polo', 'QUALITY SHILO POLO')], max_length=100, verbose_name='Product Name'),
        ),
    ]
